version: "3.8"
networks:
  swiths-nt:

services:
  # app:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:8080"
  #   command: sh -c "java -jar app/app.jar"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
  #     SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
  #     SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  #   networks:
  #     - swiths-nt
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Seoul"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./backend/src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/data.sql
    command:
      - --lower-case-table-names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    # restart: always
    networks:
      - swiths-nt

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - swiths-nt
