version: "3.8"
networks:
  swiths-nt:

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: swiths
      MYSQL_DATABASE: swiths_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
      TZ: "Asia/Seoul"

    command: ["--lower-case-table-names=1"]
    # restart: always
    networks:
      - swiths-nt
  redis:
    image: redis-alpine:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - swiths-nt
