version: "3.8"
networks:
  swiths-nt:

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: swiths
      MYSQL_DATABASE: swiths_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
      TZ: "Asia/Seoul"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./backend/src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/data.sql
    command:
      - --lower-case-table-names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    # restart: always
    networks:
      - swiths-nt

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - swiths-nt
