# Change api server port
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config.activate.on-profile: default
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/swiths_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: userpw

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
