# get data from env file

# Change api server port
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config.activate.on-profile: default
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: swithssss@gmail.com # 앱 비밀번호 발급받은 google 계정
    password:  buknnkphdciklbpi # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/swiths_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: userpw

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always

# application-local.yml

