# Change api server port
server:
  port: 4000
  servlet:
    context-path: /api

spring:
  # DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: System.getenv("MYSQL_URL")
    username: System.getenv("MYSQL_USER")
    password: System.getenv("MYSQL_PASSWORD")

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
