# Change api server port
server:
  port: 4000
  servlet:
    context-path: /api

spring:
  # DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
