name: Run DevServer

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "feature/44-fix-devserver"

jobs:
  run-dev-server:
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      # Gradle Build 실행
      - name: Build with Gradle
        run: ./gradlew clean build --debug
        working-directory: ${{ env.working-directory }}

      - name: run Database
        run: docker-compose up -d

      - name: Run DevServer
        run: java -jar build/libs/swiths_api-0.0.1-SNAPSHOT.jar
        working-directory: ${{ env.working-directory }}
