name: Run DevServer

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      # Gradle Build 실행
      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ${{ env.working-directory }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: swiths-dev-build
          path: ${{ env.working-directory }}/build/libs/swiths_api-0.0.1-SNAPSHOT.jar

      - name: Upload docker compose file
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose
          path: ./docker-compose-dev.yml

  run-server:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download docker compose file
        uses: actions/download-artifact@v3
        with:
          name: docker-compose
          path: ${{ secrets.DEV_RUN_DIR }}

      - name: set .env file
        run: |
          echo "$DEV_ENV" > .env
          echo "$DEV_PATH_GECKO" >> .env
        working-directory: ${{ secrets.DEV_RUN_DIR }}
        env:
          DEV_ENV: ${{ secrets.DEV_ENV }}
          PATH_GECKO: ${{ secrets.DEV_PATH_GECKO }}

      - name: run Database
        run: docker compose -f docker-compose-dev.yml up -d
        working-directory: ${{ secrets.DEV_RUN_DIR }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: swiths-dev-build
          path: ${{ secrets.DEV_RUN_DIR }}/build/libs

      - name: Run DevServer
        run: java -jar swiths_api-0.0.1-SNAPSHOT.jar &
        working-directory: ${{ secrets.DEV_RUN_DIR }}/build/libs
